---
- name: install packages
  become: yes
  become_user: root
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ install_packages }}"

- name: install oh my zsh
  ansible.builtin.import_tasks: oh-my-zsh.yml

- name: install and configure vim
  ansible.builtin.import_tasks: vim.yml

- name: install and configure tmux
  ansible.builtin.import_tasks: tmux.yml
