---
- name: copy configuration files
  ansible.builtin.copy:
    src: .vimrc
    dest: ~/.vimrc
    backup: yes
    mode: '0640'

- name: clean vim bundle directory
  ansible.builtin.file:
    path: "~/.vim/bundle"
    state: absent

- name: clone minpac
  ansible.builtin.git:
    repo: "https://github.com/k-takata/minpac.git"
    version: master
    dest: "~/.vim/pack/minpac/opt/minpac"

- name: check nord theme presence
  ansible.builtin.stat:
    path: "~/.vim/pack/minpac/start/vim/colors/nord.vim"
  register: nord_theme_presence

- name: vim nord color scheme
  block:
    - name: set desktop environment dependent variables
      ansible.builtin.include_vars: "vars/nord_{{ desktop_environment }}.yml"

    - name: clone nord color scheme
      ansible.builtin.git:
        repo: "{{ nord_repo }}"
        version: master
        dest: ~/nord-terminal

    - name: install nord color theme
      ansible.builtin.shell: "~/nord-terminal/{{ nord_script }}"
      args:
        chdir: ~/nord-terminal

    - name: remove nord color theme installer
      ansible.builtin.file:
        path: ~/nord-terminal
        state: absent

  when: not nord_theme_presence.stat.exists

- name: vim minpac update
  ansible.builtin.shell: |
    vim "+call PackInit()" "+call minpac#update('', {'do': 'qall'})"
  args:
    executable: /bin/bash
  changed_when: false

- name: use ripgrep for fzf
  ansible.builtin.blockinfile:
    path: ~/.zshrc
    insertafter: EOF
    marker: '# {mark} ANSIBLE MANAGED BLOCK - fzf'
    block: "{{ fzf_default | string }}"
    create: yes

- name: make vim default editor
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    insertafter: EOF
    regexp: "^export EDITOR="
    line: "export EDITOR=vim"
    create: yes
