---
- name: install base packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ install_packages }}"

- name: place device event configuration files
  ansible.builtin.copy:
    src: files/udev/
    dest: /etc/udev/
    owner: root
    group: root
    mode: '0644'

- name: update hardware database index
  ansible.builtin.command: system-hwdb update
  change_when: false
