---
- name: install base packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ install_packages }}"

- name: place device event configuration files
  ansible.builtin.copy:
    src: files/udev/
    dest: /etc/udev/

- name: create ssh directory
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: "~{{ username }}/.ssh"
    state: directory
    mode: '0700'

- name: generate an openssh keypair
  become: yes
  become_user: "{{ username }}"
  community.crypto.openssh_keypair:
    path: "~{{ username }}/.ssh/id_ssh_rsa"
    regenerate: full_idempotence
  register: ssh_keypair

- name: log public key
  ansible.builtin.debug:
    msg: "{{ ssh_keypair.public_key }}"

- name: upload public key to github
  ansible.builtin.pause:
    prompt: "Upload public key to Github"
  when: ((authorizations | default({})).github | default(false)) | bool

- name: install oh my zsh
  ansible.builtin.import_tasks: oh-my-zsh.yml

- name: clone password store
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.import_tasks: pass.yml
  when: ((authorizations | default({})).pass | default(false)) | bool

- name: setup gpg
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.import_tasks: gpg.yml
  when: ((authorizations | default({})).gpg | default(false)) | bool
