---
- name: install base packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ install_packages }}"

- name: place device event configuration files
  ansible.builtin.copy:
    src: files/udev/
    dest: /etc/udev/
