---
authorizations:
    pass: true
    github: true
    gpg: true
repo: git@github.com:myorg/password-store.git
gpg_email: "john.doe@example.com"
gpg_public_key: |
  -----BEGIN PGP PUBLIC KEY BLOCK-----
  -----END PGP PUBLIC KEY BLOCK-----

gpg_signing_key: |
  -----BEGIN PGP PRIVATE KEY BLOCK-----
  -----END PGP PRIVATE KEY BLOCK-----

gpg_ownertrust: |
  1234:6:
gpg_passphrase: secret
