---
- name: install packages
  become: yes
  become_user: root
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ install_packages }}"

- name: create ssh directory
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: '0700'

- name: generate and upload ssh keypair
  block:
    - name: generate an openssh keypair
      community.crypto.openssh_keypair:
        path: "~/.ssh/id_rsa_github"
        regenerate: full_idempotence
      register: ssh_keypair

    - name: log public key
      ansible.builtin.debug:
        msg: "{{ ssh_keypair.public_key }}"
      when: ssh_keypair.changed

    - name: upload public key to github
      ansible.builtin.pause:
        prompt: "Upload public key to Github"
      when: ssh_keypair.changed

  when: private_ssh_key is not defined

- name: copy ssh keypair
  ansible.builtin.copy:
    content: "{{ private_ssh_key }}"
    dest: "~/.ssh/id_rsa_github"
    mode: '0600'

  when: private_ssh_key is defined

- name: clone password store
  ansible.builtin.import_tasks: pass.yml
  when: ((authorizations | default({})).pass | default(false)) | bool

- name: setup gpg
  ansible.builtin.import_tasks: gpg.yml
  when: ((authorizations | default({})).gpg | default(false)) | bool
