---
- name: install packages
  become: yes
  become_user: root
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ install_packages }}"

- name: create ssh directory
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: '0700'

- name: generate an openssh keypair
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_ssh_rsa"
    regenerate: full_idempotence
  register: ssh_keypair

- name: log public key
  ansible.builtin.debug:
    msg: "{{ ssh_keypair.public_key }}"

- name: upload public key to github
  ansible.builtin.pause:
    prompt: "Upload public key to Github"
  when: ((authorizations | default({})).github | default(false)) | bool

- name: clone password store
  ansible.builtin.import_tasks: pass.yml
  when: ((authorizations | default({})).pass | default(false)) | bool

- name: setup gpg
  ansible.builtin.import_tasks: gpg.yml
  when: ((authorizations | default({})).gpg | default(false)) | bool
