---
- name: check if .password-store exists
  ansible.builtin.stat:
    path: "~/.password-store"
  register: password_store_presence

- name: clone private password store
  ansible.builtin.git:
    repo: "{{ repo }}"
    version: master
    dest: "~/.password-store"
    accept_hostkey: yes
    key_file: "~/.ssh/id_rsa_github"
  when: not password_store_presence.stat.exists
