---
install_packages:
  - bzip2
  - bzip2-devel
  - git
  - gnupg2
  - man
  - openssl
  - openssl-devel
  - pass
  - pinentry-tty
  - systemd-udev
  - xclip
  - xz
  - xz-devel
  - zlib-devel
  - zsh
