---
- name: Converge
  hosts: all

  vars:
    user: user1

  pre_tasks:
    - name: install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - zsh

    - name: create user
      become: true
      ansible.builtin.user:
        name: "{{ user }}"
        createhome: true
        shell: /bin/zsh

  roles:
    # replace these tasks with whatever you find suitable to test
    - role: credentials
      become: yes
      become_user: "{{ user }}"
