---
- name: Converge
  hosts: all

  vars:
    user: user1

  pre_tasks:
    - name: install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - zsh

    - name: create user
      become: true
      ansible.builtin.user:
        name: "{{ user }}"
        createhome: true
        shell: /bin/zsh

  roles:
    # replace these tasks with whatever you find suitable to test
    - role: credentials
      become: yes
      become_user: "{{ user }}"
      vars:
        private_ssh_key: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
          NhAAAAAwEAAQAAAYEA3TcmlKqQgf/9y9y3vbcaCzVUQpnIfqXJk+P/MMR1gTtq3tzrqs/X
          M0q0ovk4BUckGwqLkUxguywO5/Vn7RaCoP5zYadaye7aa0rqGMb/DFAJjqv9cCw2wQ5cIA
          tqtP1a/S6/OhoZqd8x4FDAL7vlbMsFCk6+L5gZUwMOem+J9uNmUs9u5v50z55ttGWBxiMp
          ROOSr80XDz5qj0hInOoNLefvoW3Iz+SU2XgQOtI7cO4jLG6FkVfR7Csn28k0/q8IwCfPEI
          rXEW3Q51WX3dPPHu0UGjA3htIvyz94+ztl01Nn02KPtHuB1HGDmcLfJhPN+R215e2P6LKV
          bvKdZ8VNdu8lA3BBjtVo7ziU7uWSSjIE8ttrf+oTBnDOPycxRenpnRSFbr49dhS+bcstOZ
          kPYw4RO7IhCvQ6X8kJf2FiqupdGiFkI1qU3hAMhsHCuWyPrtC41S0WqabIQofY3+d1P9PF
          FKwqsKCO0/pPsvKznSrqlFexuMy9cWIFlVzpMUcRAAAFkMXtGlXF7RpVAAAAB3NzaC1yc2
          EAAAGBAN03JpSqkIH//cvct723Ggs1VEKZyH6lyZPj/zDEdYE7at7c66rP1zNKtKL5OAVH
          JBsKi5FMYLssDuf1Z+0WgqD+c2GnWsnu2mtK6hjG/wxQCY6r/XAsNsEOXCALarT9Wv0uvz
          oaGanfMeBQwC+75WzLBQpOvi+YGVMDDnpvifbjZlLPbub+dM+ebbRlgcYjKUTjkq/NFw8+
          ao9ISJzqDS3n76FtyM/klNl4EDrSO3DuIyxuhZFX0ewrJ9vJNP6vCMAnzxCK1xFt0OdVl9
          3Tzx7tFBowN4bSL8s/ePs7ZdNTZ9Nij7R7gdRxg5nC3yYTzfkdteXtj+iylW7ynWfFTXbv
          JQNwQY7VaO84lO7lkkoyBPLba3/qEwZwzj8nMUXp6Z0UhW6+PXYUvm3LLTmZD2MOETuyIQ
          r0Ol/JCX9hYqrqXRohZCNalN4QDIbBwrlsj67QuNUtFqmmyEKH2N/ndT/TxRSsKrCgjtP6
          T7Lys50q6pRXsbjMvXFiBZVc6TFHEQAAAAMBAAEAAAGANpUVkWgWeOUbj7IZqhdkNzDE5h
          wAwvMQLkv62uMWpTjucSfshDx9Olwr/uxkPLUlfQCYmFTSp0xDL0u3hWHhAG1YNdevyJSF
          UyTsZwmuw7B58ziPs55NMkxjQcrfXOIIkeD3cRQgkfAO4+y4xu5jOPlM+JKeTasHUJq391
          DPJ1pLlJI3KIrPcq0CH5lOMH/bfnJybqs5jdrWOx1YQVNkxhds4pVuj5E0gwYjZwgZf49a
          oWtxzH9xPgcV8h6O02qHVjSygUBCNEykFpHfZihWFryz4Q1/QOx1SFUdwXF/RgcBpNRyOn
          tcW3HSPRqVlj/8snrTu9w4AAhyxBis20MsdEvHhFtxf04Vo5NpiA0iviL2tY4sHd72UpYz
          gfhpyzjun2A+nfIJP0McWjgJMybXsMffZHIXrlSc8EvCyfJIb4Dtl8Lsak7Ig5rR5DyjhB
          b6TGv09XUmVqtgOp3FyyhcEKQsrVTa4RHbi0v/0l9j9nf/G7KMRR39APF29WgouIWZAAAA
          wQC1dp/AgkDULmBhC4RHk/F1tu9esLZVLCnyvH7BqOhGYOEDm3cMQwJmPeMC7JhXEL2ZrS
          FgvmarmR6JqyQD6mi4HLKP5s2L57K6MkXQnf3KmrZHTXDpSfFLYroHgGU5KkrZNsAlU7h6
          qo5JZ/7H1NcgoeVAK+3qpoL6GDXWFie8B9+RYlengFlZmBRmrLoGwRzbZN+rnBEEmDeVvY
          1O6G/1xOMIY+relLH8uu7Z9O/B4K5CDJgKXRL8qBngcfLbBIgAAADBAPZdEsPRgyTExtEm
          prxmtNjYhHWXIO4r5HzqSl+wcZkdCbKZfvr31Jipom1WKOmFGk1LPEBr6ssSibqA7KJQ2h
          Xibtw4PFIRV6ZEeabqywVIzEkf1fZZ4fOBnwg/d4Q6nfKENuBcVOozktryqpOzmalHa+fs
          PgBoVYSTX+lpo9J4LNgMPWfggTAjL9eAxr91HNt885xSMMsVwMuN2em2EIQ0quzKdNKI+v
          fRKpm7HZLG25EFyXhkpMwxmy0FYEXYhQAAAMEA5d5ClunDr0DO06coSU0uzke/8LFulHmF
          HgZvj/1nJ4DV3N4iyAnFNIb35opKJKCTgqsXaQwltZk5weTK7vra4G632FD3CGMBuGOk71
          Rg/qP6SZNIaBYzWFCJmb3Arj2GwnaQtlCBua6IMHzXKxmmddvTSdLBdtf9ojrIU7BbKsdk
          GkZJ8gU8nvOTF4a1kCiA6rzYOJOInjV6dqLanz66UyWfoyTGwLimvINlszyJNig5GO9ju6
          xFl2aLXtFKlMAdAAAAFGFuc2libGVAYmNkMWI5OTkzZGNlAQIDBAUG
          -----END OPENSSH PRIVATE KEY-----

      repo: git@github.com:brainfartlab/pass-store-mock.git

      gpg_email: john.doe@example.com
      gpg_public_key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        mDMEZHEPaBYJKwYBBAHaRw8BAQdA8lm8sEbhw4rnnI1UuEC7nTFsN5lDoWqZKS8E
        95g2+sq0NkpvaG4gRG9lIChmb3IgdGVzdGluZyBwdXJwb3NlcykgPGpvaG4uZG9l
        QGV4YW1wbGUuY29tPoiTBBMWCgA7FiEEeLU7f9WstBrfHPAW9zFcrEnsOs4FAmRx
        D2gCGwMFCwkIBwICIgIGFQoJCAsCBBYCAwECHgcCF4AACgkQ9zFcrEnsOs6znQEA
        6+EM4jygvbYTwNz8AN+Pd39oE7JMiJkadXMvl6+O8OsBAMFn6tD9PQSv3v0reJkg
        1cC1IIe3j9lEV65+5OboL0gJuDgEZHEPaBIKKwYBBAGXVQEFAQEHQHaFqZjFKpOZ
        NNn9Ea6+PlxIAU1DEIrSMfnIcb4zTmozAwEIB4h4BBgWCgAgFiEEeLU7f9WstBrf
        HPAW9zFcrEnsOs4FAmRxD2gCGwwACgkQ9zFcrEnsOs4YXgD/QuOz9YhDABNdMtx9
        DWGK/smXoLYCvCzOO/65wQ5ewgcA/0fj5hZZTyE8o6iWiuELWzy5sPxeKJNy8bha
        Abc4UZQN
        =dHLT
        -----END PGP PUBLIC KEY BLOCK-----
      gpg_signing_key: |
        -----BEGIN PGP PRIVATE KEY BLOCK-----

        lIYEZHEPaBYJKwYBBAHaRw8BAQdA8lm8sEbhw4rnnI1UuEC7nTFsN5lDoWqZKS8E
        95g2+sr+BwMCd78zz6BI5Sj/Bxz2e26wIzgdxqWtdMK45Dyj01gmwVeX84FipXDx
        jexss8QC0vzeUAmY47molNW7tooAnLo8hYOELUudAW2LyyYEEmaGxbQ2Sm9obiBE
        b2UgKGZvciB0ZXN0aW5nIHB1cnBvc2VzKSA8am9obi5kb2VAZXhhbXBsZS5jb20+
        iJMEExYKADsWIQR4tTt/1ay0Gt8c8Bb3MVysSew6zgUCZHEPaAIbAwULCQgHAgIi
        AgYVCgkICwIEFgIDAQIeBwIXgAAKCRD3MVysSew6zrOdAQDr4QziPKC9thPA3PwA
        3493f2gTskyImRp1cy+Xr47w6wEAwWfq0P09BK/e/St4mSDVwLUgh7eP2URXrn7k
        5ugvSAmciwRkcQ9oEgorBgEEAZdVAQUBAQdAdoWpmMUqk5k02f0Rrr4+XEgBTUMQ
        itIx+chxvjNOajMDAQgH/gcDAlfA0Xhr5qSa/0YSe3JEnv80gUQMuuHf9Dq5AsNv
        wcROwX+IsaeMKLXRRavlVLY/Dr60sbMQuW8wp2hfjaHI17pYCdyYR6F56K/n+slx
        0WOIeAQYFgoAIBYhBHi1O3/VrLQa3xzwFvcxXKxJ7DrOBQJkcQ9oAhsMAAoJEPcx
        XKxJ7DrOGF4A/0Ljs/WIQwATXTLcfQ1hiv7Jl6C2Arwszjv+ucEOXsIHAP9H4+YW
        WU8hPKOolorhC1s8ubD8XiiTcvG4WgG3OFGUDQ==
        =DDR2
        -----END PGP PRIVATE KEY BLOCK-----
      gpg_ownertrust: |
        78B53B7FD5ACB41ADF1CF016F7315CAC49EC3ACE:6:
      gpg_passphrase: mypassphrase
