name: "Molecule test"

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  molecule:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies.
        run: pip3 install yamllint ansible-lint ansible "molecule[lint,docker]"

      - name: Install Galaxy dependencies.
        run: ansible-galaxy collection install community.podman

      - name: Run molecule
        working-directory: brainfartlab/overlord/roles/base
        run: molecule test
