name: "Molecule test"

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  gather:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: |
          roles=$(ls | jq -R -s -c 'split("\n")[:-1]')
          echo "action_state=$roles" >> "$GITHUB_OUTPUT"

  consume-roles:
    needs: [ gather ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(gather.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"

  molecule:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies.
        run: pip3 install yamllint ansible-lint ansible "molecule[lint,podman]" molecule-podman

      - name: Install Galaxy dependencies.
        run: ansible-galaxy collection install containers.podman

      - name: Run molecule
        working-directory: brainfartlab/overlord/roles/base
        run: molecule test
