name: "Molecule test"

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  molecule:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup molecule
        run: pip install molecule

      - name: Run molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_working_dir: "brainfartlab/overlord/brainfartlab/overlord/roles/base"
